"""The managed .gitignore block is a COMMITTED file shared by every clone, not this machine's state.

Reproduces what happened on a fresh clone: installing one skill rewrote the block from the local manifest alone, so
the lines for the skills installed on other machines vanished, and every CRLF in the file became LF.
"""

from __future__ import annotations

import importlib.util
import os
import pathlib
import shutil
import sys
import tempfile
import unittest

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from install import GITIGNORE_MARKER_END, GITIGNORE_MARKER_START, SkillInstaller  # noqa: E402

BASELINE = "# Byte-compiled\r\n__pycache__/\r\n*.py[cod]\r\n"
OTHERS = ["alpha", "beta"]


def _committed_gitignore() -> bytes:
    block = [
        GITIGNORE_MARKER_START,
        "# Ignore local Claude workspace commands generated by skill-manager",
        ".claude/commands/skill-manager/",
        "# Ignore local Claude workspace settings written by skill-manager",
        ".claude/settings.json",
        "# Ignore the local skill-manager installation manifest",
        ".claude/skill-manager-manifest.json",
        "# Ignore skill directories installed and managed by skill-manager",
        *[f".claude/skills/{name}/" for name in OTHERS],
        GITIGNORE_MARKER_END,
    ]
    return (BASELINE + "\r\n" + "\r\n".join(block) + "\r\n").encode("utf-8")


def _load_skill_manager_post_install():
    path = REPO / "skills" / "skill-manager" / "post_install.py"
    spec = importlib.util.spec_from_file_location("skill_manager_post_install_shared", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class TestGitignoreBlockSharedAcrossMachines(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.mkdtemp()
        self.published = os.path.join(self.tmp, "published")
        skill = os.path.join(self.published, "workflow", "gamma")
        os.makedirs(skill)
        with open(os.path.join(skill, "SKILL.md"), "w", encoding="utf-8") as handle:
            handle.write("# gamma\n")
        self.project = os.path.join(self.tmp, "fresh-clone")
        os.makedirs(self.project)
        self.gitignore = os.path.join(self.project, ".gitignore")
        with open(self.gitignore, "wb") as handle:
            handle.write(_committed_gitignore())
        self.installer = SkillInstaller(self.published, lambda _config: {})

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp)

    def _bytes(self) -> bytes:
        with open(self.gitignore, "rb") as handle:
            return handle.read()

    def test_installing_on_a_fresh_clone_keeps_the_other_machines_lines(self) -> None:
        self.assertTrue(self.installer.install_skill("workflow/gamma", self.project))
        content = self._bytes().decode("utf-8")
        for name in [*OTHERS, "gamma"]:
            self.assertIn(f".claude/skills/{name}/", content)

    def test_line_endings_and_baseline_survive_byte_for_byte(self) -> None:
        self.installer.install_skill("workflow/gamma", self.project)
        data = self._bytes()
        self.assertTrue(data.startswith(BASELINE.encode("utf-8")))
        self.assertEqual(data.count(b"\n"), data.count(b"\r\n"), "a bare LF was introduced")

    def test_uninstall_drops_only_its_own_line(self) -> None:
        self.installer.install_skill("workflow/gamma", self.project)
        self.installer.uninstall_skill("gamma", self.project)
        self.assertEqual(self._bytes(), _committed_gitignore())

    def test_rewriting_an_unchanged_block_is_a_no_op(self) -> None:
        self.installer.ensure_managed_gitignore_entries(self.project)
        self.assertEqual(self._bytes(), _committed_gitignore())

    def test_skill_manager_post_install_keeps_the_lines_and_endings_too(self) -> None:
        post_install = _load_skill_manager_post_install()
        post_install._ensure_gitignore_entries(self.project)  # pylint: disable=protected-access
        self.assertEqual(self._bytes(), _committed_gitignore())


if __name__ == "__main__":
    unittest.main()
